# Generated by Django 5.2.7 on 2025-11-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='media_type',
            new_name='source_type',
        ),
    ]
