# Generated by Django 5.2.7 on 2025-11-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_media_type_note_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inspiration',
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
