# Generated by Django 5.2.7 on 2025-11-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inspiration_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.inspiration')),
            ],
            options={
                'db_table': 'screenshot',
            },
        ),
    ]
