# Generated by Django 5.2.7 on 2025-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspiration',
            old_name='title',
            new_name='essence',
        ),
        migrations.AddField(
            model_name='inspiration',
            name='source_title',
            field=models.CharField(default='Unknown Source', max_length=255),
            preserve_default=False,
        ),
    ]
