# Generated by Django 5.2.7 on 2025-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_title_inspiration_essence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
