# Generated by Django 5.2.7 on 2025-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_screenshot_extracted_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='content',
        ),
        migrations.AddField(
            model_name='inspiration',
            name='user_thoughts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
