# Generated by Django 5.2.7 on 2025-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_inspiration_content_inspiration_user_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='inspiration_quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
