# Generated by Django 5.2.7 on 2025-11-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inspiration_inspiration_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspiration',
            old_name='inspiration_quote',
            new_name='quote',
        ),
    ]
