# Generated by Django 5.2.7 on 2025-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_inspiration_quote_inspiration_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
