# Generated by Django 4.2.7 on 2026-05-12 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_inspiration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, default='', max_length=512)),
                ('isbn', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('source_type', models.CharField(default='book', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_source',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn__gt', '')), fields=('user', 'isbn'), name='core_source_unique_user_isbn'),
        ),
    ]
