# Generated by Django 4.2.7 on 2026-05-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='source',
            name='core_source_unique_user_isbn',
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn__gt', '')), fields=('user', 'isbn'), name='source_unique_user_isbn'),
        ),
        migrations.AlterModelTable(
            name='source',
            table='source',
        ),
    ]
