# Generated by Django 4.2.7 on 2026-05-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_inspiration_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=50)),
                ('context_sentence', models.TextField(help_text='The sentence from the book where the word was encountered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_entries', to='core.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'word_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
