# Generated by Django 4.2.7 on 2026-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_word_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordentry',
            name='is_inspiring',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this word appears in the home spotlight rotation.'),
        ),
    ]
