# Generated by Django 4.2.7 on 2026-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_word_entry_is_inspiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordentry',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, guests can see this word on the public home spotlight.'),
        ),
    ]
