# Generated by Django 4.2.7 on 2026-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_word_entry_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='context_sentence',
            field=models.TextField(blank=True, default='', help_text='The sentence from the book where the word was encountered.'),
        ),
    ]
